encode-av1, x11 forwaring

diff --git a/.bash/encode-av1 b/.bash/encode-av1
--- a/.bash/encode-av1
+++ b/.bash/encode-av1
@@ -1,27 +1,45 @@
 #!/bin/bash
 
 # find /run/media/heas/Expansion/ -name '*.mp4' -size +500M -exec bash -c 'encode-av1 "$0" /home/heas/not_converted' {} \;
-[[ ! -f "$1" ]] && echo invalid file && exit 1
-[[ -z "$2" ]] && echo please provide directory for unprocessed files && exit 1
-[[ ! -d "$2" ]] && echo invalid directory for unprocessed files && exit 1
+# find  /run/media/heas/Expansion/ -name *.mp4 ! -name '*.invalid.*' ! -name '*.not_converted*' -size +500M -exec bash -c 'encode-av1 "$0" /home/heas/not_converted' {} \;
 
+[[ ! -f "$1" ]] && echo invalid file && exit 1
+if echo "$1" | grep -q '\.invalid\.'; then
+    echo invalid
+    exit 1
+fi
+if echo "$1" | grep -q '\.not_converted'; then
+    echo not_converted
+    exit 1
+fi
+if echo "$1" | grep -q '\.av1\.'; then
+    echo already in av1 format
+    exit 1
+fi
+
+#[[ -z "$2" ]] && echo please provide directory for unprocessed files && exit 1
+#[[ ! -d "$2" ]] && echo invalid directory for unprocessed files && exit 1
 MYTMPDIR="$(mktemp -d)"
 trap 'rm -rf -- "$MYTMPDIR"' EXIT
 
+FNAME="$1"
+FNAME_BASE=${FNAME%.*}
+FNAME_EXT=${FNAME##*.}
+
 ffprobe_temp_file=$(mktemp --tmpdir=${MYTMPDIR})
 ffprobe "$1" 2>$ffprobe_temp_file # | echo ffprobe "$1" failed && exit 1
-[[ $? -ne 0 ]] && echo ffprobe "$1" failed && exit 1
+[[ $? -ne 0 ]] && echo ffprobe "$1" failed && mv "$1" "${FNAME_BASE}.invalid.${FNAME_EXT}" && exit 1
 
 grep -qi encoder.*libsvtav1 $ffprobe_temp_file
-[[ $? -eq 0 ]] && echo "$1" already in av1 format && exit 1
+[[ $? -eq 0 ]] && echo "$1" already in av1 format && mv "$1" "${FNAME_BASE}.av1.${FNAME_EXT}" && exit 1
 # echo $1 && echo exiting && exit 1
 
 base_name=$(basename $1)
 echo $base_name
 
 ffmpeg_temp_file=$(mktemp --suffix .mp4 --tmpdir=${MYTMPDIR})
-ffmpeg -y -i "$1" -c:s mov_text -c:v libsvtav1 -crf 30 $ffmpeg_temp_file
-[[ $? -ne 0 ]] && echo ffmpeg conversion of "$1" failed && exit 1
+ffmpeg -err_detect explode -xerror -y -i "$1" -c:s mov_text -c:v libsvtav1 -crf 30 $ffmpeg_temp_file
+[[ $? -ne 0 ]] && echo ffmpeg conversion of "$1" failed && mv "$1" "${FNAME_BASE}.invalid.${FNAME_EXT}" && exit 1
 
 ffprobe $ffmpeg_temp_file 2>$ffprobe_temp_file # | echo ffprobe "$1" failed && exit 1
 [[ $? -ne 0 ]] && echo ffprobe on converted file failed && exit 1
@@ -31,5 +49,5 @@ new_size=`du -k "$ffmpeg_temp_file" | cut -f1`
 echo $org_size
 echo $new_size
 [[ $org_size -gt $new_size ]] && echo Copying. New file size less than original. && cp $ffmpeg_temp_file "$1" && exit 1
-[[ $org_size -lt $new_size ]] && echo Skipping. New file size greater than original. && mv "$1" "$2/${base_name}"
+[[ $org_size -lt $new_size ]] && echo Skipping. New file size greater than original. && mv "$1" "${FNAME_BASE}.not_converted_to_av1.${FNAME_EXT}"
 
